name: Ember.js CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Build on Node.js 16

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: latest

    - name: Install Dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

  npm_publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: latest

    - name: Install Dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Set up npm
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

    - name: Publish
      run: npm publish --access public

  github_publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Configure npm for GitHub registry
        run: |
          echo "@fleetbase:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Publish to GitHub registry
        run: npm publish
